# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Package

on:
  push:
    branches: [ pypi_releases ]

  pull_request:
    branches: [ pypi_releases ]

jobs:
  uploading:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip twine

    - name: Setup Source Distribution
      run: python setup.py sdist

    - name: Publish Package
      run: |
        python -m twine upload -u "${{ secrets.PyPI_USER }}" -p "${{ secrets.PyPI_PASS }}" dist/*
